tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/certificate.crt
        keyFile: /etc/certs/certificate.key
  certificates:
    - certFile: /etc/certs/certificate.crt
      keyFile: /etc/certs/certificate.key
      stores:
        - default